// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeha-IbaC6Iqw5-YRUOpLvdS57Bo40ge8',
    appId: '1:818568455467:web:12c2a81ee1edc53f1a116e',
    messagingSenderId: '818568455467',
    projectId: 'hobby-179eb',
    authDomain: 'hobby-179eb.firebaseapp.com',
    storageBucket: 'hobby-179eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFZkBkLPFchYEBrmamT1W6KjO0jhSANE',
    appId: '1:818568455467:android:39e4a87fe9e976aa1a116e',
    messagingSenderId: '818568455467',
    projectId: 'hobby-179eb',
    storageBucket: 'hobby-179eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavohRsVas9zCjARXt3Veg_EtYgZvg90s',
    appId: '1:818568455467:ios:d3376d73675778041a116e',
    messagingSenderId: '818568455467',
    projectId: 'hobby-179eb',
    storageBucket: 'hobby-179eb.firebasestorage.app',
    iosBundleId: 'com.example.hobby',
  );
}
